builds:
  - id: bonesay
    dir: cmd
    main: ./bonesay/main.go
    binary: bonesay
    env:
      - CGO_ENABLED=0
    ldflags: -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: arm
        goarm: 7
      - goos: windows
        goarch: arm
        goarm: 7
  - id: cowthink
    dir: cmd
    main: ./cowthink/main.go
    binary: cowthink
    env:
      - CGO_ENABLED=0
    ldflags: -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: arm
        goarm: 7
      - goos: windows
        goarch: arm
        goarm: 7

archives:
- builds:
  - bonesay
  - cowthink
  name_template: 'bonesay_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
  replacements:
    darwin: macOS
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
  - goos: windows
    format: zip
  files:
  - LICENSE
  - doc/bonesay.1

brews:
- name: neo-bonesay
  tap:
    owner: Code-Hex
    name: homebrew-tap
    token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
  homepage: https://github.com/anthonycuervo23/bonesay
  description: "Fast, funny, everyone wanted? new bonesay!!"
  folder: Formula
  install: |
    bin.install "bonesay"
    bin.install "cowthink"
    man1.install Dir["doc/bonesay.1"]

nfpms:
  - license: Artistic License 2.0
    maintainer: Kei Kamikawa <x00.x7f.x86@gmail.com>
    homepage: https://github.com/anthonycuervo23/bonesay
    bindir: /usr/local/bin
    description: "Fast, funny, everyone wanted? new bonesay!!"
    formats:
      - apk
      - deb
      - rpm
    contents:
      - src: "doc/bonesay.1"
        dst: "/usr/share/man/man1/bonesay.1"

checksum:
  name_template: 'bonesay_checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch
