on:
  pull_request_review:
    types:
      - submitted

jobs:
  lgtm:
    name: LGTM
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    steps:
    - name: bonesay LGTM
      uses: anthonycuervo23/bonesay-action@v1.0.2
      with:
        message: 'LGTM'
        bone: 'random'
        bonesay_on_comment: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}